name: PullRequest

on: [pull_request]

jobs:
  buildTest:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Build project
        run:  ./gradlew genIntellijRuns